// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apieyhjxuojlxzsqmxgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwaWV5aGp4dW9qbHh6c3FteGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTA3MzQsImV4cCI6MjA2NTU4NjczNH0.X7lJKIHVf75W_wiR9UGxfd1ZvlgN95snqBhrzg8mv6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);